language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.3
    env: TOXENV=py33
  - python: 3.4
    env: TOXENV=py34
install:
- if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0 tox==3.1.3;
  fi
- pip install tox
script: tox
env:
  global:
    secure: Skx+U0mjyXWLBBVwdQg7d+dQP9doDlbQFtMKVuKoMdrHePfLJBeev9DVDX9e3La3G9E7G+zLIBJR79rwm5XLy1WW+N4dtfbSP23ZBi/qXMAsAes8dMsrypelx8KTE5OS444rOyu7pKmU1RT4xg9H4cXGInCepewMGvEVxKy/uB558mj2lVj1zOu+yBSJCIg9MM8M3P4a9cgDbd3zjKVvqefvATIrQmKCewFeNhifkQzkdhKXq7hZll4gpWLf8+IB05Ky34IO2z7ROREdECNxU03ZF0mWDvVLK49iAykfrYMb3esF6609amKH+h+6Q1ZLPJZGuXY65rZFR5z8LjLiZqekm4vMLH3+BEiXeO+prIQIC6ZVEqs05HAZK9TRZfZYh1fFgP2ea2+eDrFcTXUVnbUUjB8KLIjtHDINg/ij7TPBwudET4P5VJ5H0o2GBUybUjsfxIhB26U2ydcyp6c28DSlceBERbn+TYxrXp4NOyBkEKN1cwpzSWHteYdiHRL39lX3cub2a8MIhCbWh+SBMYJ4aHuOB7OM+bdu64a/mIS+HL+T6i2c1a9LY2YpLN6BaoBjFJVvakvMqOvIgDeBzY3LxDbWrinF9ZijyAgLuxQq2Biwu7z8blGED3XfPKdJuyxK3Ji3E65ziL0vXQ+2e2iIMhuuFFrCdbfYWPQSoys=
