language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
install:
- if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0 tox==3.1.3;
  fi
- pip install tox
script: tox
env:
  global:
    secure: nVB1o73pnu+eBpkVezewXkXCIkiL62g6kWfxt2dHR/w+XI6BlwdpeebPM9UpvZFkW+RDaEhCL6NvFFHlBzXhh9qiPXm2IDG0MDu5SAhaTr6iM5LotYhcyvah1KQiGvUNzuvMiIpVe+CXbJ2VsLWNz9Aa5DE53onK8NNHqLtsgInztDUxrAes5C1bwudslucxcQYP9Q4bpBfKDnLv58cpBI3UfcUTsm0PKESrsUDc3kHokLgXirzpNOHKbBc5286H6R9jZOHc1IeJC51JK7tQTZFJQPT9JPX1KB2q6u5N/BMDlJ670Mk5BOIfPRoYlxU0efLH5G2SVR46HmAhLEXLtPknmGt+o3vY2cPpaoD+tu8YJBKrFYJZ3l1Zr8ZYcKaQMQWpWmyFXWWGLuxqkK3feDvARtxPyZVlKnYTKOaJN5+SgXliRQCshA2CTYdGgSyuwYedur50SULzP7Q8FtKwTgVPJWXsKG307WNsbmZ3zN8cJEweKnahg+YneeRaVKDL4qlNjG8VVCcl5s656L6K/q9fnFVeYdqlox9B/ZpYMjXO5QwhRbfrTBYIZM9atqA6UVoJcRTRaFWNWJBWsvp+LJx8pVxq3KjyGuV4Vgmj8Uzct8uUF0R6iwDOjUd7k3Sk8olwxaf2u55DrQ4WbvwVZGjyQscQu6Rqgqo2fHBywXk=
